import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import ResultCard from '../components/ResultCard';

/**
 * PublicLookup - Public page for viewing shared lookup results.
 * 
 * This page allows anyone with a UUID to view a lookup result without authentication.
 * It's the destination for shareable links generated by the "Copy link" button.
 * 
 * Features:
 * - Fetches lookup data by UUID from public API
 * - Displays full result using ResultCard
 * - Handles 404 errors gracefully
 * - Provides navigation back to landing page
 */
const PublicLookup = () => {
  const { uuid } = useParams();
  const navigate = useNavigate();
  const [lookup, setLookup] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    fetchLookup();
  }, [uuid]);

  const fetchLookup = async () => {
    setLoading(true);
    setError('');

    try {
      const apiUrl = process.env.REACT_APP_API_URL || 'http://localhost:8000';
      const res = await axios.get(`${apiUrl}/api/lookup/${uuid}`);
      
      // Transform the data to match ResultCard's expected format
      const transformedData = {
        target: res.data.target,
        type: res.data.type,
        resolved_ip: res.data.resolved_ip,
        geo: res.data.result?.geo || {},
        risk_level: res.data.risk_level,
        uuid: res.data.uuid,
        created_at: res.data.created_at,
        dns_records: res.data.result?.dns_records || [],
      };
      
      setLookup(transformedData);
    } catch (err) {
      console.error('Failed to fetch lookup:', err);
      if (err.response?.status === 404) {
        setError('Lookup not found. The link may be invalid or the lookup may have been deleted.');
      } else {
        setError('Failed to load lookup. Please try again.');
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-950 to-black text-gray-100 p-4 sm:p-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8 gap-4">
        <div>
          <h1 className="text-4xl font-bold bg-gradient-to-r from-cyan-400 to-cyan-600 bg-clip-text text-transparent">
            LinkGuard
          </h1>
          <p className="text-gray-400 mt-1">Shared Lookup Result</p>
        </div>
        <div className="flex gap-3">
          <button
            onClick={() => navigate('/')}
            className="px-6 py-2.5 bg-gray-800 text-gray-300 rounded-lg font-medium hover:bg-gray-700 transform hover:scale-105 transition-all duration-200 shadow-lg hover:shadow-cyan-500/20"
          >
            ← Back to Home
          </button>
          <button
            onClick={() => navigate('/login')}
            className="px-6 py-2.5 bg-gradient-to-r from-cyan-600 to-cyan-700 text-white rounded-lg font-medium hover:from-cyan-700 hover:to-cyan-800 transform hover:scale-105 transition-all duration-200 shadow-lg hover:shadow-cyan-500/20"
          >
            Log In
          </button>
        </div>
      </div>

      {/* Loading State */}
      {loading && (
        <div className="bg-gray-900/80 backdrop-blur-md p-12 rounded-2xl border border-gray-800/50 shadow-2xl">
          <div className="flex flex-col items-center justify-center">
            <span className="text-4xl mb-4 animate-spin">⏳</span>
            <p className="text-gray-400 text-lg">Loading lookup...</p>
          </div>
        </div>
      )}

      {/* Error State */}
      {error && !loading && (
        <div className="bg-gray-900/80 backdrop-blur-md p-12 rounded-2xl border border-gray-800/50 shadow-2xl">
          <div className="flex flex-col items-center justify-center">
            <span className="text-6xl mb-4">❌</span>
            <h2 className="text-2xl font-bold text-white mb-3">Lookup Not Found</h2>
            <p className="text-gray-400 text-center mb-6 max-w-md">
              {error}
            </p>
            <button
              onClick={() => navigate('/')}
              className="px-8 py-3 bg-gradient-to-r from-cyan-600 to-cyan-700 text-white font-semibold rounded-xl hover:from-cyan-500 hover:to-cyan-600 transform hover:scale-105 transition-all duration-200 shadow-lg hover:shadow-cyan-500/50"
            >
              Go to Home Page
            </button>
          </div>
        </div>
      )}

      {/* Success State - Display Result */}
      {lookup && !loading && !error && (
        <div>
          <ResultCard result={lookup} showShareLink={true} />
          
          {/* Call to Action */}
          <div className="mt-8 bg-gradient-to-r from-cyan-900/50 to-blue-900/50 backdrop-blur-md p-8 rounded-2xl border border-cyan-700/50 shadow-2xl">
            <div className="text-center">
              <h2 className="text-2xl font-bold text-white mb-3">
                Want to analyze your own links?
              </h2>
              <p className="text-gray-300 mb-6">
                Create a free account to save your lookup history, add custom labels, and share results with your team.
              </p>
              <div className="flex justify-center gap-4">
                <button
                  onClick={() => navigate('/register')}
                  className="px-8 py-3 bg-gradient-to-r from-cyan-600 to-cyan-700 text-white font-semibold rounded-xl hover:from-cyan-500 hover:to-cyan-600 transform hover:scale-105 transition-all duration-200 shadow-lg hover:shadow-cyan-500/50"
                >
                  Create Free Account
                </button>
                <button
                  onClick={() => navigate('/')}
                  className="px-8 py-3 bg-gray-800 text-gray-300 font-semibold rounded-xl hover:bg-gray-700 transform hover:scale-105 transition-all duration-200"
                >
                  Try It Now
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default PublicLookup;
